export const FETCH_PROVIDER = "FETCH_PROVIDER"
export const FETCH_REQUIREMENTCUSTOMER = "FETCH_REQUIREMENTCUSTOMER"
export const FETCH_SERVICES = "FETCH_SERVICES"
export const ADD_DAYSTART = "ADD_DAYSTART"
